apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
  namespace: bilvantisai
data:
  ETCD_AUTO_COMPACTION_MODE: "revision"
  ETCD_AUTO_COMPACTION_RETENTION: "1000"
  ETCD_QUOTA_BACKEND_BYTES: "4294967296"
  ETCD_SNAPSHOT_COUNT: "50000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-standalone
  namespace: bilvantisai
spec:
  selector:
    app: milvus-standalone
  ports:
    - name: milvus
      port: 19530
      targetPort: 19530
    - name: metrics
      port: 9091
      targetPort: 9091
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
  namespace: bilvantisai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-standalone
  template:
    metadata:
      labels:
        app: milvus-standalone
    spec:
      nodeSelector:
        role: primary
      containers:
      - name: milvus
        image: us-central1-docker.pkg.dev/bt-dev-388506/milvus2/milvus:v2.2.11
        command: ["milvus", "run", "standalone"]
        ports:
        - containerPort: 19530
        - containerPort: 9091
        env:
        - name: ETCD_ENDPOINTS
          value: "localhost:2379"
        - name: MINIO_ADDRESS
          value: "localhost:9000"
        volumeMounts:
        - name: milvus-data
          mountPath: /var/lib/milvus
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9091
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      - name: etcd
        image: us-central1-docker.pkg.dev/bt-dev-388506/milvus2/etcd:v3.5.5
        command:
        - etcd
        - -advertise-client-urls=http://127.0.0.1:2379
        - -listen-client-urls=http://0.0.0.0:2379
        - --data-dir=/etcd
        ports:
        - containerPort: 2379
        envFrom:
        - configMapRef:
            name: milvus-config
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd
        livenessProbe:
          httpGet:
            path: /health
            port: 2379
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      - name: minio
        image: us-central1-docker.pkg.dev/bt-dev-388506/milvus2/minio:RELEASE.2023-03-20T20-16-18Z
        args: ["server", "/minio_data"]
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: milvus-config
        volumeMounts:
        - name: minio-data
          mountPath: /minio_data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 3
      volumes:
      - name: milvus-data
        persistentVolumeClaim:
          claimName: milvus-pvc
      - name: etcd-data
        persistentVolumeClaim:
          claimName: etcd-pvc
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: milvus-config
#   namespace: bilvantisai
# data:
#   ETCD_AUTO_COMPACTION_MODE: "revision"
#   ETCD_AUTO_COMPACTION_RETENTION: "1000"
#   ETCD_QUOTA_BACKEND_BYTES: "4294967296"
#   ETCD_SNAPSHOT_COUNT: "50000"
#   MINIO_ACCESS_KEY: "minioadmin"
#   MINIO_SECRET_KEY: "minioadmin"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: milvus-standalone
#   namespace: bilvantisai
# spec:
#   selector:
#     app: milvus
#   ports:
#     - name: milvus
#       port: 19530
#       targetPort: 19530
#     - name: metrics
#       port: 9091
#       targetPort: 9091
#   type: ClusterIP
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: milvus
#   namespace: bilvantisai
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: milvus
#   template:
#     metadata:
#       labels:
#         app: milvus
#     spec:
#       nodeSelector:
#         role: primary
#       containers:
#       - name: milvus
#         image: us-docker.pkg.dev/bt-dev-388506/milvus/milvus:v2.2.11
#         command: ["milvus", "run", "standalone"]
#         ports:
#         - containerPort: 19530
#         - containerPort: 9091
#         env:
#         - name: ETCD_ENDPOINTS
#           value: "localhost:2379"
#         - name: MINIO_ADDRESS
#           value: "localhost:9000"
#         volumeMounts:
#         - name: milvus-data
#           mountPath: /var/lib/milvus
#         livenessProbe:
#           httpGet:
#             path: /healthz
#             port: 9091
#           initialDelaySeconds: 30
#           periodSeconds: 30
#           timeoutSeconds: 10
#           failureThreshold: 3

#       - name: etcd
#         image: us-docker.pkg.dev/bt-dev-388506/milvus/etcd:v3.5.5
#         command:
#         - etcd
#         - -advertise-client-urls=http://127.0.0.1:2379
#         - -listen-client-urls=http://0.0.0.0:2379
#         - --data-dir=/etcd
#         ports:
#         - containerPort: 2379
#         envFrom:
#         - configMapRef:
#             name: milvus-config
#         volumeMounts:
#         - name: etcd-data
#           mountPath: /etcd
#         livenessProbe:
#           httpGet:
#             path: /health
#             port: 2379
#           initialDelaySeconds: 30
#           periodSeconds: 30
#           timeoutSeconds: 10
#           failureThreshold: 3

#       - name: minio
#         image: us-docker.pkg.dev/bt-dev-388506/milvus/minio:RELEASE.2023-03-20T20-16-18Z
#         args: ["server", "/minio_data"]
#         ports:
#         - containerPort: 9000
#         envFrom:
#         - configMapRef:
#             name: milvus-config
#         volumeMounts:
#         - name: minio-data
#           mountPath: /minio_data
#         livenessProbe:
#           httpGet:
#             path: /minio/health/live
#             port: 9000
#           initialDelaySeconds: 30
#           periodSeconds: 30
#           timeoutSeconds: 20
#           failureThreshold: 3

#       volumes:
#       - name: milvus-data
#         persistentVolumeClaim:
#           claimName: milvus-pvc
#       - name: etcd-data
#         persistentVolumeClaim:
#           claimName: etcd-pvc
#       - name: minio-data
#         persistentVolumeClaim:
#           claimName: minio-pvc

# # apiVersion: v1
# # kind: ConfigMap
# # metadata:
# #   name: milvus-config
# # data:
# #   ETCD_AUTO_COMPACTION_MODE: "revision"
# #   ETCD_AUTO_COMPACTION_RETENTION: "1000"
# #   ETCD_QUOTA_BACKEND_BYTES: "4294967296"
# #   ETCD_SNAPSHOT_COUNT: "50000"
# #   MINIO_ACCESS_KEY: "minioadmin"
# #   MINIO_SECRET_KEY: "minioadmin"
# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: milvus-standalone
# # spec:
# #   selector:
# #     app: milvus
# #   ports:
# #     - name: milvus
# #       port: 19530
# #       targetPort: 19530
# #     - name: metrics
# #       port: 9091
# #       targetPort: 9091
# #   type: ClusterIP
# # ---
# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: milvus
# # spec:
# #   replicas: 1
# #   selector:
# #     matchLabels:
# #       app: milvus
# #   template:
# #     metadata:
# #       labels:
# #         app: milvus
# #     spec:
# #       containers:
# #       - name: milvus
# #         image: milvusdb/milvus:v2.2.11
# #         command: ["milvus", "run", "standalone"]
# #         ports:
# #         - containerPort: 19530
# #         - containerPort: 9091
# #         env:
# #         - name: ETCD_ENDPOINTS
# #           value: "localhost:2379"
# #         - name: MINIO_ADDRESS
# #           value: "localhost:9000"
# #         volumeMounts:
# #         - name: milvus-data
# #           mountPath: /var/lib/milvus
# #         livenessProbe:
# #           httpGet:
# #             path: /healthz
# #             port: 9091
# #           initialDelaySeconds: 30
# #           periodSeconds: 30
# #           timeoutSeconds: 10
# #           failureThreshold: 3

# #       - name: etcd
# #         image: us-docker.pkg.dev/bt-dev-388506/milvus/etcd:v3.5.5
# #         command:
# #         - etcd
# #         - -advertise-client-urls=http://127.0.0.1:2379
# #         - -listen-client-urls=http://0.0.0.0:2379
# #         - --data-dir=/etcd
# #         ports:
# #         - containerPort: 2379
# #         envFrom:
# #         - configMapRef:
# #             name: milvus-config
# #         volumeMounts:
# #         - name: etcd-data
# #           mountPath: /etcd
# #         livenessProbe:
# #           httpGet:
# #             path: /health
# #             port: 2379
# #           initialDelaySeconds: 30
# #           periodSeconds: 30
# #           timeoutSeconds: 10
# #           failureThreshold: 3

# #       - name: minio
# #         image: us-docker.pkg.dev/bt-dev-388506/milvus/minio:RELEASE.2023-03-20T20-16-18Z
# #         args: ["server", "/minio_data"]
# #         ports:
# #         - containerPort: 9000
# #         envFrom:
# #         - configMapRef:
# #             name: milvus-config
# #         volumeMounts:
# #         - name: minio-data
# #           mountPath: /minio_data
# #         livenessProbe:
# #           httpGet:
# #             path: /minio/health/live
# #             port: 9000
# #           initialDelaySeconds: 30
# #           periodSeconds: 30
# #           timeoutSeconds: 20
# #           failureThreshold: 3

# #       volumes:
# #       - name: milvus-data
# #         persistentVolumeClaim:
# #           claimName: milvus-pvc
# #       - name: etcd-data
# #         persistentVolumeClaim:
# #           claimName: etcd-pvc
# #       - name: minio-data
# #         persistentVolumeClaim:
# #           claimName: minio-pvc
