apiVersion: v1
kind: PersistentVolume
metadata:
  name: milvus-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: surekha-storage-class
  gcePersistentDisk:
    pdName: "milvus-disk"   # Ensure this disk exists in your GCP project
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: surekha-storage-class
  gcePersistentDisk:
    pdName: "etcd-disk"     # Ensure this disk exists in your GCP project
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: surekha-storage-class
  gcePersistentDisk:
    pdName: "minio-disk"    # Ensure this disk exists in your GCP project
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: surekha-storage-class
  gcePersistentDisk:
    pdName: "mongo-disk"    # Ensure this disk exists in your GCP project
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: surekha-storage-class
  gcePersistentDisk:
    pdName: "elasticsearch-disk"  # Ensure this disk exists in your GCP project
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chroma-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: surekha-storage-class
  gcePersistentDisk:
    pdName: "chroma-disk"    # Ensure this disk exists in your GCP project
    fsType: ext4



# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: milvus-pv
# spec:
#   capacity:
#     storage: 100Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: surekha-storage-class
#   gcePersistentDisk:
#     pdName: "milvus-disk"
#     fsType: ext4

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: etcd-pv
# spec:
#   capacity:
#     storage: 100Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: surekha-storage-class
#   gcePersistentDisk:
#     pdName: "etcd-disk"
#     fsType: ext4

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: minio-pv
# spec:
#   capacity:
#     storage: 100Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: surekha-storage-class
#   gcePersistentDisk:
#     pdName: "minio-disk"
#     fsType: ext4

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongo-pv
# spec:
#   capacity:
#     storage: 100Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: surekha-storage-class
#   gcePersistentDisk:
#     pdName: "mongo-disk"
#     fsType: ext4

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: elasticsearch-pv
# spec:
#   capacity:
#     storage: 100Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: surekha-storage-class
#   gcePersistentDisk:
#     pdName: "elasticsearch-disk"
#     fsType: ext4

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: chroma-pv
# spec:
#   capacity:
#     storage: 100Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: surekha-storage-class
#   gcePersistentDisk:
#     pdName: "chroma-disk"
#     fsType: ext4
