# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fastapi-app
#   namespace: genie
#   labels:
#     app: fastapi-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: fastapi-app
#   template:
#     metadata:
#       labels:
#         app: fastapi-app
#     spec:
#       nodeSelector:
#         role: tertiary
#       containers:
#         - name: fastapi-app
#           image: us-central1-docker.pkg.dev/pre-onboarding-427811/genie-backend/genie-backend:latest
#           ports:
#             - containerPort: 3000
#           envFrom:
#             - configMapRef:
#                 name: app-config
#             - secretRef:
#                 name: app-secrets
#           resources:
#             limits:
#               cpu: "1"
#               memory: "512Mi"
#             requests:
#               cpu: "500m"
#               memory: "256Mi"
#           env:
#             - name: PYTHONUNBUFFERED
#               value: "1"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: fastapi-app-service
# spec:
#   selector:
#     app: fastapi-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3000
#   type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: genie
  labels:
    app: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      nodeSelector:
        role: secondary
      containers:
        - name: fastapi-app
          image: us-central1-docker.pkg.dev/bt-dev-388506/bil-genie/genie-backend-27-01-2025:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
            # - secretRef:
            #     name: app-secrets
            - secretRef:
                name: app-secrets # Re
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
  namespace: genie
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 34.122.71.143

 