apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-git-app-hpa
  namespace: gitkb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-git-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5  # Trigger scaling if CPU utilization exceeds 5% of allocated CPU
