apiVersion: v1
kind: ConfigMap
metadata:
  name: gitkb-config
  namespace: gitkb
data:
  GIT_PYTHON_REFRESH: "quiet"
  DB_NAME: "code_embeddings"
  DB_EMBEDDINGS_COLLECTION: "code_files"
  DB_REPONAMES_COLLECTION: "repos"
  AUTH_DB_USER_DB: "user_db"
  AUTH_DB_USER_COLLECTION: "users"
  METRICS_DB: "metrics_db"
  METRICS_DB_COLLECTION: "metrics"
  AUTH_JWT_ALGORITHM: "HS256"
  AUTH_JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  MONGO_URI: "mongodb+srv://bhaskargujju:genie%40123@cluster0.ccc2u.mongodb.net/"
  AUTH_JWT_SECRET_KEY: "Genie-Bilvantis"