# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: python-git-app
#   namespace: gitkb
#   labels:
#     app: python-git-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: python-git-app
#   template:
#     metadata:
#       labels:
#         app: python-git-app
#     spec:
#       nodeSelector:
#         kubernetes.io/role: secondary
#       containers:
#       - name: python-git-app
#         image: python-git-app:latest  # Replace with your actual image name and tag
#         ports:
#         - containerPort: 3001
#         resources:
#           requests:
#             cpu: "200m"
#             memory: "256Mi"
#           limits:
#             cpu: "500m"
#             memory: "512Mi"
#         envFrom:
#           - configMapRef:
#               name: python-git-app-config
#           - secretRef:
#               name: python-git-app-secrets

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: python-git-app-service
#   namespace: gitkb
# spec:
#   selector:
#     app: python-git-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3001
#   type: ClusterIP


apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-git-app
  namespace: gitkb
  labels:
    app: python-git-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-git-app
  template:
    metadata:
      labels:
        app: python-git-app
    spec:
      nodeSelector:
        role: secondary  # Ensure this nodeSelector matches your node labels
      containers:
      - name: python-git-app
        image: us-central1-docker.pkg.dev/bt-dev-388506/bil-gitkb/gitkb-27-01-2025:latest  # Replace with your actual image name and tag
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
          - configMapRef:
              name: gitkb-config
          - secretRef:
              name: gitkb-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: python-git-app-service
  namespace: gitkb
spec:
  selector:
    app: python-git-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer  # Changed from ClusterIP to LoadBalancer
  loadBalancerIP: 34.57.225.101  # Replace with your actual reserved static IP
